### ISSUE TITLE
库安装问题

### ISSUE THREAD

**Issue by FRC1221** [zhangzjn/EMO#13]
Traceback (most recent call last):
  File "D:\yolov5-7.0\yolov5-7.0\models\yolo.py", line 24, in <module>
    from models.common import *
  File "D:\yolov5-7.0\yolov5-7.0\models\common.py", line 1853, in <module>
    from timm.models.layers.activations import *
ModuleNotFoundError: No module named 'timm.models.layers.activations'

**Comment by lxtGH** [comment]
Please check your timm version.

**Comment by moyans** [comment]
pip install timm==0.6.13
